id: DDBC31AD6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:59:44+00:00'
last_modified: '2022-05-29T08:39:46.030814+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '4541':
      image_group_id: I1PD95922
      title: ཕུང་པོ་ལྔའི་རྣམ་པར་འགྲེལ་པ།
      total_pages: 1517
      order: 77
      base_file: 4541.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
