id: P60E7CFED
initial_creation_type: ocr
source_metadata:
  volumes:
    b0ecab0edf224f0890ad583cbcf879d2:
      base_file: v077.txt
      image_group_id: I1PD95922
      title: ཕུང་པོ་ལྔའི་རྣམ་པར་འགྲེལ་པ།
      total_pages: 1517
      volume_number: 77
